[debug]
address = "127.0.0.1"
port = 8080
workers = 4
keep_alive = 5
log_level = "debug"
ident = "rfile"
limits = { bytes = "8KiB", data-form = "256MiB", file = "256MiB", form = "64KiB", json = "1MiB", msgpack = "1MiB", string = "8KiB" }

[release]
address = "127.0.0.1"
port = 80
workers = 8
keep_alive = 5
log_level = "normal"
ident = "rfile"
limits = { bytes = "8KiB", data-form = "256MiB", file = "256MiB", form = "64KiB", json = "1MiB", msgpack = "1MiB", string = "8KiB" }